# Generated by Django 4.2.3 on 2023-08-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_prod',
        ),
        migrations.AlterField(
            model_name='product',
            name='price_prod',
            field=models.PositiveIntegerField(blank=True, help_text='Введите цену продукта в рублях', null=True, verbose_name='Цена'),
        ),
    ]
