# Generated by Django 4.2.3 on 2023-09-04 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('set_published', 'Can publish product')], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
